import type {
  AgingBucketAmount,
  Customer,
  CustomerDetail,
  CustomerId,
  CustomerInput,
  CustomerQuery,
  CustomerSummary,
  CustomerUpdate,
  DebtDetail,
  DebtNoticeDocument,
  DebtRow,
  DebtSummary,
  DocumentHeader,
  DocumentLine,
  Invoice,
  InvoiceDetail,
  InvoiceDocument,
  InvoiceId,
  InvoiceInput,
  InvoiceLine,
  InvoiceLineInput,
  InvoiceQuery,
  Notification,
  NotificationId,
  NotificationQuery,
  Payment,
  PaymentId,
  PaymentInput,
  PaymentQuery,
  Product,
  ProductId,
  ProductInput,
  ProductQuery,
  ProductUpdate,
  ProofId,
  ProofInput,
  ProofQuery,
  Receipt,
  ReceiptDocument,
  ReceiptId,
  Satang,
  SettingsInput,
  ShopSettings,
  Timestamp,
  TransferProof,
} from "@/backend";

export type {
  AgingBucketAmount,
  Customer,
  CustomerDetail,
  CustomerId,
  CustomerInput,
  CustomerQuery,
  CustomerSummary,
  CustomerUpdate,
  DebtDetail,
  DebtNoticeDocument,
  DebtRow,
  DebtSummary,
  DocumentHeader,
  DocumentLine,
  Invoice,
  InvoiceDetail,
  InvoiceDocument,
  InvoiceId,
  InvoiceInput,
  InvoiceLine,
  InvoiceLineInput,
  InvoiceQuery,
  Notification,
  NotificationId,
  NotificationQuery,
  Payment,
  PaymentId,
  PaymentInput,
  PaymentQuery,
  Product,
  ProductId,
  ProductInput,
  ProductQuery,
  ProductUpdate,
  ProofId,
  ProofInput,
  ProofQuery,
  Receipt,
  ReceiptDocument,
  ReceiptId,
  Satang,
  SettingsInput,
  ShopSettings,
  Timestamp,
  TransferProof,
};

export {
  AgingBucket,
  InvoiceStatus,
  NotificationKind,
  PaymentMethod,
  PaymentStatus,
  ProofStatus,
  UserRole,
} from "@/backend";

/** The two top-level areas of the app. */
export type AppArea = "manager" | "customer";

/** A single entry in the sidebar navigation. */
export interface NavItem {
  label: string;
  to: string;
  icon: string;
  /** Only shown to the manager role. */
  managerOnly?: boolean;
}
