/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgingBucket = { 'days1to30' : null } |
  { 'over90' : null } |
  { 'days31to60' : null } |
  { 'current' : null } |
  { 'days61to90' : null };
export interface AgingBucketAmount { 'bucket' : AgingBucket, 'amount' : Satang }
export interface Cell { 'value' : Value, 'name' : string }
export interface Customer {
  'id' : CustomerId,
  'loginPrincipal' : [] | [Principal],
  'active' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'creditLimit' : Satang,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface CustomerDetail {
  'aging' : Array<AgingBucketAmount>,
  'customer' : Customer,
  'invoiceCount' : bigint,
  'outstandingBalance' : Satang,
  'paymentCount' : bigint,
}
export type CustomerId = bigint;
export interface CustomerInput {
  'name' : string,
  'creditLimit' : Satang,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface CustomerQuery {
  'descending' : [] | [boolean],
  'sortBy' : [] | [string],
  'search' : [] | [string],
}
export interface CustomerSummary {
  'id' : CustomerId,
  'loginPrincipal' : [] | [Principal],
  'active' : boolean,
  'invoiceCount' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'creditLimit' : Satang,
  'address' : string,
  'notes' : string,
  'outstandingBalance' : Satang,
  'phone' : string,
}
export interface CustomerUpdate {
  'active' : boolean,
  'name' : string,
  'creditLimit' : Satang,
  'address' : string,
  'notes' : string,
  'phone' : string,
}
export interface DebtDetail {
  'customerName' : string,
  'aging' : Array<AgingBucketAmount>,
  'invoices' : Array<Invoice>,
  'outstandingBalance' : Satang,
  'customerId' : CustomerId,
  'phone' : string,
}
export interface DebtNoticeDocument {
  'customerName' : string,
  'aging' : Array<AgingBucketAmount>,
  'customerPhone' : string,
  'promptPayRef' : string,
  'bankName' : string,
  'accountName' : string,
  'customerAddress' : string,
  'invoices' : Array<DocumentLine>,
  'outstandingBalance' : Satang,
  'accountNumber' : string,
  'issuedAt' : Timestamp,
  'amountInWords' : string,
  'header' : DocumentHeader,
}
export interface DebtRow {
  'customerName' : string,
  'aging' : Array<AgingBucketAmount>,
  'invoiceCount' : bigint,
  'oldestDueAt' : [] | [Timestamp],
  'outstandingBalance' : Satang,
  'customerId' : CustomerId,
  'phone' : string,
}
export interface DebtSummary {
  'aging' : Array<AgingBucketAmount>,
  'totalOutstanding' : Satang,
  'customerCount' : bigint,
}
export interface DocumentHeader {
  'taxId' : string,
  'address' : string,
  'shopName' : string,
  'phone' : string,
}
export interface DocumentLine {
  'unit' : string,
  'lineTotal' : Satang,
  'description' : string,
  'quantity' : bigint,
  'unitPrice' : Satang,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Invoice {
  'id' : InvoiceId,
  'customerName' : string,
  'status' : InvoiceStatus,
  'total' : Satang,
  'outstanding' : Satang,
  'lines' : Array<InvoiceLine>,
  'amountPaid' : Satang,
  'notes' : string,
  'number' : string,
  'customerId' : CustomerId,
  'issuedAt' : Timestamp,
  'dueAt' : Timestamp,
  'subtotal' : Satang,
}
export interface InvoiceDetail {
  'proofIds' : Array<ProofId>,
  'payments' : Array<Payment>,
  'invoice' : Invoice,
}
export interface InvoiceDocument {
  'customerName' : string,
  'total' : Satang,
  'customerPhone' : string,
  'outstanding' : Satang,
  'lines' : Array<DocumentLine>,
  'amountPaid' : Satang,
  'customerAddress' : string,
  'notes' : string,
  'number' : string,
  'issuedAt' : Timestamp,
  'dueAt' : Timestamp,
  'amountInWords' : string,
  'subtotal' : Satang,
  'header' : DocumentHeader,
}
export type InvoiceId = bigint;
export interface InvoiceInput {
  'lines' : Array<InvoiceLineInput>,
  'notes' : string,
  'customerId' : CustomerId,
  'issuedAt' : Timestamp,
  'dueAt' : Timestamp,
}
export interface InvoiceLine {
  'unit' : string,
  'lineTotal' : Satang,
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : Satang,
}
export interface InvoiceLineInput {
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface InvoiceQuery {
  'status' : [] | [InvoiceStatus],
  'search' : [] | [string],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
  'customerId' : [] | [CustomerId],
}
export type InvoiceStatus = { 'paid' : null } |
  { 'unpaid' : null } |
  { 'overdue' : null } |
  { 'partiallyPaid' : null };
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'body' : string,
  'kind' : NotificationKind,
  'createdAt' : Timestamp,
  'read' : boolean,
}
export type NotificationId = bigint;
export type NotificationKind = { 'invoiceOverdue' : null } |
  { 'paymentRecorded' : null } |
  { 'proofApproved' : null } |
  { 'proofRejected' : null } |
  { 'proofUploaded' : null };
export interface NotificationQuery {
  'limit' : [] | [bigint],
  'unreadOnly' : [] | [boolean],
}
export interface Payment {
  'id' : PaymentId,
  'customerName' : string,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'createdAt' : Timestamp,
  'reference' : string,
  'invoiceId' : InvoiceId,
  'invoiceNumber' : string,
  'customerId' : CustomerId,
  'amount' : Satang,
  'paidAt' : Timestamp,
  'proofId' : [] | [ProofId],
}
export type PaymentId = bigint;
export interface PaymentInput {
  'method' : PaymentMethod,
  'reference' : string,
  'invoiceId' : InvoiceId,
  'amount' : Satang,
  'paidAt' : Timestamp,
}
export type PaymentMethod = { 'other' : null } |
  { 'cash' : null } |
  { 'bankTransfer' : null };
export interface PaymentQuery {
  'status' : [] | [PaymentStatus],
  'search' : [] | [string],
  'customerId' : [] | [CustomerId],
}
export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Product {
  'id' : ProductId,
  'sku' : string,
  'active' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'unit' : string,
  'category' : string,
  'unitPrice' : Satang,
}
export type ProductId = bigint;
export interface ProductInput {
  'sku' : string,
  'name' : string,
  'unit' : string,
  'category' : string,
  'unitPrice' : Satang,
}
export interface ProductQuery {
  'search' : [] | [string],
  'category' : [] | [string],
  'activeOnly' : [] | [boolean],
}
export interface ProductUpdate {
  'sku' : string,
  'active' : boolean,
  'name' : string,
  'unit' : string,
  'category' : string,
  'unitPrice' : Satang,
}
export type ProofId = bigint;
export interface ProofInput {
  'note' : string,
  'invoiceId' : InvoiceId,
  'imageKey' : string,
  'transferredAt' : Timestamp,
  'amount' : Satang,
}
export interface ProofQuery {
  'status' : [] | [ProofStatus],
  'customerId' : [] | [CustomerId],
}
export type ProofStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Receipt {
  'id' : ReceiptId,
  'customerName' : string,
  'method' : PaymentMethod,
  'reference' : string,
  'invoiceId' : InvoiceId,
  'invoiceNumber' : string,
  'number' : string,
  'paymentId' : PaymentId,
  'customerId' : CustomerId,
  'issuedAt' : Timestamp,
  'amount' : Satang,
  'paidAt' : Timestamp,
}
export interface ReceiptDocument {
  'customerName' : string,
  'method' : PaymentMethod,
  'reference' : string,
  'invoiceNumber' : string,
  'customerAddress' : string,
  'number' : string,
  'issuedAt' : Timestamp,
  'amount' : Satang,
  'amountInWords' : string,
  'header' : DocumentHeader,
}
export type ReceiptId = bigint;
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Satang = bigint;
export interface SettingsInput {
  'taxId' : string,
  'defaultPaymentTermsDays' : bigint,
  'promptPayRef' : string,
  'bankName' : string,
  'accountName' : string,
  'invoicePrefix' : string,
  'address' : string,
  'shopName' : string,
  'accountNumber' : string,
  'phone' : string,
  'receiptPrefix' : string,
}
export interface ShopSettings {
  'taxId' : string,
  'defaultPaymentTermsDays' : bigint,
  'promptPayRef' : string,
  'bankName' : string,
  'accountName' : string,
  'invoicePrefix' : string,
  'address' : string,
  'shopName' : string,
  'accountNumber' : string,
  'phone' : string,
  'receiptPrefix' : string,
}
export type Timestamp = bigint;
export interface TransferProof {
  'id' : ProofId,
  'customerName' : string,
  'status' : ProofStatus,
  'note' : string,
  'invoiceId' : InvoiceId,
  'reviewNote' : string,
  'reviewedAt' : [] | [Timestamp],
  'imageKey' : string,
  'invoiceNumber' : string,
  'paymentId' : [] | [PaymentId],
  'customerId' : CustomerId,
  'transferredAt' : Timestamp,
  'amount' : Satang,
  'uploadedAt' : Timestamp,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Approve a proof, creating the linked payment.
   */
  'approveProof' : ActorMethod<[ProofId], [] | [TransferProof]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Bind a login principal to a customer account (manager only).
   */
  'bindCustomerLogin' : ActorMethod<[CustomerId, Principal], [] | [Customer]>,
  /**
   * / Bind the signed-in caller's own principal to an unclaimed customer account.
   */
  'claimCustomerAccount' : ActorMethod<[CustomerId], [] | [Customer]>,
  /**
   * / Count unread manager notifications.
   */
  'countUnreadManagerNotifications' : ActorMethod<[], bigint>,
  /**
   * / Count unread notifications for the signed-in customer.
   */
  'countUnreadMyNotifications' : ActorMethod<[], bigint>,
  /**
   * / Create a customer account with a provisioned login.
   */
  'createCustomer' : ActorMethod<[CustomerInput], Customer>,
  /**
   * / Create an invoice for a customer.
   */
  'createInvoice' : ActorMethod<[InvoiceInput], Invoice>,
  /**
   * / Create a product.
   */
  'createProduct' : ActorMethod<[ProductInput], Product>,
  /**
   * / Deactivate a product without deleting its invoice history.
   */
  'deactivateProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Return the API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch a customer detail view.
   */
  'getCustomer' : ActorMethod<[CustomerId], [] | [CustomerDetail]>,
  /**
   * / Fetch one customer's debt detail.
   */
  'getCustomerDebt' : ActorMethod<[CustomerId], [] | [DebtDetail]>,
  /**
   * / Build the printable debt notice document for a customer.
   */
  'getDebtNoticeDocument' : ActorMethod<
    [CustomerId],
    [] | [DebtNoticeDocument]
  >,
  /**
   * / Aggregate outstanding balance and aging across all customers.
   */
  'getDebtSummary' : ActorMethod<[], DebtSummary>,
  /**
   * / Fetch an invoice detail view.
   */
  'getInvoice' : ActorMethod<[InvoiceId], [] | [InvoiceDetail]>,
  /**
   * / Build the printable invoice document for an invoice.
   */
  'getInvoiceDocument' : ActorMethod<[InvoiceId], [] | [InvoiceDocument]>,
  /**
   * / Resolve the signed-in caller's own customer account.
   */
  'getMyCustomer' : ActorMethod<[], [] | [Customer]>,
  /**
   * / Fetch the signed-in customer's own debt detail.
   */
  'getMyDebt' : ActorMethod<[], [] | [DebtDetail]>,
  /**
   * / Fetch one of the signed-in customer's own invoices.
   */
  'getMyInvoice' : ActorMethod<[InvoiceId], [] | [Invoice]>,
  /**
   * / Fetch one of the signed-in customer's own receipts.
   */
  'getMyReceipt' : ActorMethod<[ReceiptId], [] | [Receipt]>,
  /**
   * / Fetch a single payment.
   */
  'getPayment' : ActorMethod<[PaymentId], [] | [Payment]>,
  /**
   * / Fetch a single product.
   */
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  /**
   * / Fetch a single transfer proof.
   */
  'getProof' : ActorMethod<[ProofId], [] | [TransferProof]>,
  /**
   * / Build the printable receipt document for a receipt.
   */
  'getReceiptDocument' : ActorMethod<[ReceiptId], [] | [ReceiptDocument]>,
  /**
   * / Read the shop profile and bank details.
   */
  'getSettings' : ActorMethod<[], ShopSettings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List customers with search and sort applied.
   */
  'listCustomers' : ActorMethod<[CustomerQuery], Array<CustomerSummary>>,
  /**
   * / List every customer with an outstanding balance.
   */
  'listDebts' : ActorMethod<[], Array<DebtRow>>,
  /**
   * / List invoices with search, status, and date-range filters applied.
   */
  'listInvoices' : ActorMethod<[InvoiceQuery], Array<Invoice>>,
  /**
   * / List notifications for the manager.
   */
  'listManagerNotifications' : ActorMethod<
    [NotificationQuery],
    Array<Notification>
  >,
  /**
   * / List the signed-in customer's own invoices.
   */
  'listMyInvoices' : ActorMethod<[], Array<Invoice>>,
  /**
   * / List notifications for the signed-in customer.
   */
  'listMyNotifications' : ActorMethod<[NotificationQuery], Array<Notification>>,
  /**
   * / List the signed-in customer's own payments.
   */
  'listMyPayments' : ActorMethod<[], Array<Payment>>,
  /**
   * / List the signed-in customer's own receipts.
   */
  'listMyReceipts' : ActorMethod<[], Array<Receipt>>,
  /**
   * / List payments with search and status filter applied.
   */
  'listPayments' : ActorMethod<[PaymentQuery], Array<Payment>>,
  /**
   * / List products with search and category filter applied.
   */
  'listProducts' : ActorMethod<[ProductQuery], Array<Product>>,
  /**
   * / List transfer proofs awaiting or already reviewed.
   */
  'listProofs' : ActorMethod<[ProofQuery], Array<TransferProof>>,
  /**
   * / Mark every manager notification as read.
   */
  'markAllManagerNotificationsRead' : ActorMethod<[], bigint>,
  /**
   * / Mark every notification of the signed-in customer as read.
   */
  'markAllMyNotificationsRead' : ActorMethod<[], bigint>,
  /**
   * / Mark one manager notification as read.
   */
  'markManagerNotificationRead' : ActorMethod<
    [NotificationId],
    [] | [Notification]
  >,
  /**
   * / Mark one of the signed-in customer's notifications as read.
   */
  'markMyNotificationRead' : ActorMethod<[NotificationId], [] | [Notification]>,
  /**
   * / Record a manual payment against an invoice.
   */
  'recordPayment' : ActorMethod<[PaymentInput], Payment>,
  /**
   * / Reject a proof, leaving the invoice balance unchanged.
   */
  'rejectProof' : ActorMethod<[ProofId, string], [] | [TransferProof]>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Edit an existing customer account.
   */
  'updateCustomer' : ActorMethod<[CustomerId, CustomerUpdate], [] | [Customer]>,
  /**
   * / Edit an existing product.
   */
  'updateProduct' : ActorMethod<[ProductId, ProductUpdate], [] | [Product]>,
  /**
   * / Update the shop profile, bank details, and numbering settings.
   */
  'updateSettings' : ActorMethod<[SettingsInput], ShopSettings>,
  /**
   * / Upload a bank-transfer proof against an invoice.
   */
  'uploadProof' : ActorMethod<[ProofInput], TransferProof>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];