/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ProofId = IDL.Nat;
export const ProofStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const InvoiceId = IDL.Nat;
export const Timestamp = IDL.Int;
export const PaymentId = IDL.Nat;
export const CustomerId = IDL.Nat;
export const Satang = IDL.Nat;
export const TransferProof = IDL.Record({
  'id' : ProofId,
  'customerName' : IDL.Text,
  'status' : ProofStatus,
  'note' : IDL.Text,
  'invoiceId' : InvoiceId,
  'reviewNote' : IDL.Text,
  'reviewedAt' : IDL.Opt(Timestamp),
  'imageKey' : IDL.Text,
  'invoiceNumber' : IDL.Text,
  'paymentId' : IDL.Opt(PaymentId),
  'customerId' : CustomerId,
  'transferredAt' : Timestamp,
  'amount' : Satang,
  'uploadedAt' : Timestamp,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Customer = IDL.Record({
  'id' : CustomerId,
  'loginPrincipal' : IDL.Opt(IDL.Principal),
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'creditLimit' : Satang,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const CustomerInput = IDL.Record({
  'name' : IDL.Text,
  'creditLimit' : Satang,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const InvoiceLineInput = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const InvoiceInput = IDL.Record({
  'lines' : IDL.Vec(InvoiceLineInput),
  'notes' : IDL.Text,
  'customerId' : CustomerId,
  'issuedAt' : Timestamp,
  'dueAt' : Timestamp,
});
export const InvoiceStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
  'overdue' : IDL.Null,
  'partiallyPaid' : IDL.Null,
});
export const InvoiceLine = IDL.Record({
  'unit' : IDL.Text,
  'lineTotal' : Satang,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : Satang,
});
export const Invoice = IDL.Record({
  'id' : InvoiceId,
  'customerName' : IDL.Text,
  'status' : InvoiceStatus,
  'total' : Satang,
  'outstanding' : Satang,
  'lines' : IDL.Vec(InvoiceLine),
  'amountPaid' : Satang,
  'notes' : IDL.Text,
  'number' : IDL.Text,
  'customerId' : CustomerId,
  'issuedAt' : Timestamp,
  'dueAt' : Timestamp,
  'subtotal' : Satang,
});
export const ProductInput = IDL.Record({
  'sku' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'category' : IDL.Text,
  'unitPrice' : Satang,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'sku' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'category' : IDL.Text,
  'unitPrice' : Satang,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AgingBucket = IDL.Variant({
  'days1to30' : IDL.Null,
  'over90' : IDL.Null,
  'days31to60' : IDL.Null,
  'current' : IDL.Null,
  'days61to90' : IDL.Null,
});
export const AgingBucketAmount = IDL.Record({
  'bucket' : AgingBucket,
  'amount' : Satang,
});
export const CustomerDetail = IDL.Record({
  'aging' : IDL.Vec(AgingBucketAmount),
  'customer' : Customer,
  'invoiceCount' : IDL.Nat,
  'outstandingBalance' : Satang,
  'paymentCount' : IDL.Nat,
});
export const DebtDetail = IDL.Record({
  'customerName' : IDL.Text,
  'aging' : IDL.Vec(AgingBucketAmount),
  'invoices' : IDL.Vec(Invoice),
  'outstandingBalance' : Satang,
  'customerId' : CustomerId,
  'phone' : IDL.Text,
});
export const DocumentLine = IDL.Record({
  'unit' : IDL.Text,
  'lineTotal' : Satang,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : Satang,
});
export const DocumentHeader = IDL.Record({
  'taxId' : IDL.Text,
  'address' : IDL.Text,
  'shopName' : IDL.Text,
  'phone' : IDL.Text,
});
export const DebtNoticeDocument = IDL.Record({
  'customerName' : IDL.Text,
  'aging' : IDL.Vec(AgingBucketAmount),
  'customerPhone' : IDL.Text,
  'promptPayRef' : IDL.Text,
  'bankName' : IDL.Text,
  'accountName' : IDL.Text,
  'customerAddress' : IDL.Text,
  'invoices' : IDL.Vec(DocumentLine),
  'outstandingBalance' : Satang,
  'accountNumber' : IDL.Text,
  'issuedAt' : Timestamp,
  'amountInWords' : IDL.Text,
  'header' : DocumentHeader,
});
export const DebtSummary = IDL.Record({
  'aging' : IDL.Vec(AgingBucketAmount),
  'totalOutstanding' : Satang,
  'customerCount' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'other' : IDL.Null,
  'cash' : IDL.Null,
  'bankTransfer' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : PaymentId,
  'customerName' : IDL.Text,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'createdAt' : Timestamp,
  'reference' : IDL.Text,
  'invoiceId' : InvoiceId,
  'invoiceNumber' : IDL.Text,
  'customerId' : CustomerId,
  'amount' : Satang,
  'paidAt' : Timestamp,
  'proofId' : IDL.Opt(ProofId),
});
export const InvoiceDetail = IDL.Record({
  'proofIds' : IDL.Vec(ProofId),
  'payments' : IDL.Vec(Payment),
  'invoice' : Invoice,
});
export const InvoiceDocument = IDL.Record({
  'customerName' : IDL.Text,
  'total' : Satang,
  'customerPhone' : IDL.Text,
  'outstanding' : Satang,
  'lines' : IDL.Vec(DocumentLine),
  'amountPaid' : Satang,
  'customerAddress' : IDL.Text,
  'notes' : IDL.Text,
  'number' : IDL.Text,
  'issuedAt' : Timestamp,
  'dueAt' : Timestamp,
  'amountInWords' : IDL.Text,
  'subtotal' : Satang,
  'header' : DocumentHeader,
});
export const ReceiptId = IDL.Nat;
export const Receipt = IDL.Record({
  'id' : ReceiptId,
  'customerName' : IDL.Text,
  'method' : PaymentMethod,
  'reference' : IDL.Text,
  'invoiceId' : InvoiceId,
  'invoiceNumber' : IDL.Text,
  'number' : IDL.Text,
  'paymentId' : PaymentId,
  'customerId' : CustomerId,
  'issuedAt' : Timestamp,
  'amount' : Satang,
  'paidAt' : Timestamp,
});
export const ReceiptDocument = IDL.Record({
  'customerName' : IDL.Text,
  'method' : PaymentMethod,
  'reference' : IDL.Text,
  'invoiceNumber' : IDL.Text,
  'customerAddress' : IDL.Text,
  'number' : IDL.Text,
  'issuedAt' : Timestamp,
  'amount' : Satang,
  'amountInWords' : IDL.Text,
  'header' : DocumentHeader,
});
export const ShopSettings = IDL.Record({
  'taxId' : IDL.Text,
  'defaultPaymentTermsDays' : IDL.Nat,
  'promptPayRef' : IDL.Text,
  'bankName' : IDL.Text,
  'accountName' : IDL.Text,
  'invoicePrefix' : IDL.Text,
  'address' : IDL.Text,
  'shopName' : IDL.Text,
  'accountNumber' : IDL.Text,
  'phone' : IDL.Text,
  'receiptPrefix' : IDL.Text,
});
export const CustomerQuery = IDL.Record({
  'descending' : IDL.Opt(IDL.Bool),
  'sortBy' : IDL.Opt(IDL.Text),
  'search' : IDL.Opt(IDL.Text),
});
export const CustomerSummary = IDL.Record({
  'id' : CustomerId,
  'loginPrincipal' : IDL.Opt(IDL.Principal),
  'active' : IDL.Bool,
  'invoiceCount' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'creditLimit' : Satang,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'outstandingBalance' : Satang,
  'phone' : IDL.Text,
});
export const DebtRow = IDL.Record({
  'customerName' : IDL.Text,
  'aging' : IDL.Vec(AgingBucketAmount),
  'invoiceCount' : IDL.Nat,
  'oldestDueAt' : IDL.Opt(Timestamp),
  'outstandingBalance' : Satang,
  'customerId' : CustomerId,
  'phone' : IDL.Text,
});
export const InvoiceQuery = IDL.Record({
  'status' : IDL.Opt(InvoiceStatus),
  'search' : IDL.Opt(IDL.Text),
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
  'customerId' : IDL.Opt(CustomerId),
});
export const NotificationQuery = IDL.Record({
  'limit' : IDL.Opt(IDL.Nat),
  'unreadOnly' : IDL.Opt(IDL.Bool),
});
export const NotificationId = IDL.Nat;
export const NotificationKind = IDL.Variant({
  'invoiceOverdue' : IDL.Null,
  'paymentRecorded' : IDL.Null,
  'proofApproved' : IDL.Null,
  'proofRejected' : IDL.Null,
  'proofUploaded' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'kind' : NotificationKind,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
});
export const PaymentQuery = IDL.Record({
  'status' : IDL.Opt(PaymentStatus),
  'search' : IDL.Opt(IDL.Text),
  'customerId' : IDL.Opt(CustomerId),
});
export const ProductQuery = IDL.Record({
  'search' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'activeOnly' : IDL.Opt(IDL.Bool),
});
export const ProofQuery = IDL.Record({
  'status' : IDL.Opt(ProofStatus),
  'customerId' : IDL.Opt(CustomerId),
});
export const PaymentInput = IDL.Record({
  'method' : PaymentMethod,
  'reference' : IDL.Text,
  'invoiceId' : InvoiceId,
  'amount' : Satang,
  'paidAt' : Timestamp,
});
export const CustomerUpdate = IDL.Record({
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'creditLimit' : Satang,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProductUpdate = IDL.Record({
  'sku' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'category' : IDL.Text,
  'unitPrice' : Satang,
});
export const SettingsInput = IDL.Record({
  'taxId' : IDL.Text,
  'defaultPaymentTermsDays' : IDL.Nat,
  'promptPayRef' : IDL.Text,
  'bankName' : IDL.Text,
  'accountName' : IDL.Text,
  'invoicePrefix' : IDL.Text,
  'address' : IDL.Text,
  'shopName' : IDL.Text,
  'accountNumber' : IDL.Text,
  'phone' : IDL.Text,
  'receiptPrefix' : IDL.Text,
});
export const ProofInput = IDL.Record({
  'note' : IDL.Text,
  'invoiceId' : InvoiceId,
  'imageKey' : IDL.Text,
  'transferredAt' : Timestamp,
  'amount' : Satang,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'approveProof' : IDL.Func([ProofId], [IDL.Opt(TransferProof)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bindCustomerLogin' : IDL.Func(
      [CustomerId, IDL.Principal],
      [IDL.Opt(Customer)],
      [],
    ),
  'claimCustomerAccount' : IDL.Func([CustomerId], [IDL.Opt(Customer)], []),
  'countUnreadManagerNotifications' : IDL.Func([], [IDL.Nat], ['query']),
  'countUnreadMyNotifications' : IDL.Func([], [IDL.Nat], ['query']),
  'createCustomer' : IDL.Func([CustomerInput], [Customer], []),
  'createInvoice' : IDL.Func([InvoiceInput], [Invoice], []),
  'createProduct' : IDL.Func([ProductInput], [Product], []),
  'deactivateProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(CustomerDetail)], ['query']),
  'getCustomerDebt' : IDL.Func([CustomerId], [IDL.Opt(DebtDetail)], ['query']),
  'getDebtNoticeDocument' : IDL.Func(
      [CustomerId],
      [IDL.Opt(DebtNoticeDocument)],
      ['query'],
    ),
  'getDebtSummary' : IDL.Func([], [DebtSummary], ['query']),
  'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(InvoiceDetail)], ['query']),
  'getInvoiceDocument' : IDL.Func(
      [InvoiceId],
      [IDL.Opt(InvoiceDocument)],
      ['query'],
    ),
  'getMyCustomer' : IDL.Func([], [IDL.Opt(Customer)], ['query']),
  'getMyDebt' : IDL.Func([], [IDL.Opt(DebtDetail)], ['query']),
  'getMyInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
  'getMyReceipt' : IDL.Func([ReceiptId], [IDL.Opt(Receipt)], ['query']),
  'getPayment' : IDL.Func([PaymentId], [IDL.Opt(Payment)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProof' : IDL.Func([ProofId], [IDL.Opt(TransferProof)], ['query']),
  'getReceiptDocument' : IDL.Func(
      [ReceiptId],
      [IDL.Opt(ReceiptDocument)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [ShopSettings], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCustomers' : IDL.Func(
      [CustomerQuery],
      [IDL.Vec(CustomerSummary)],
      ['query'],
    ),
  'listDebts' : IDL.Func([], [IDL.Vec(DebtRow)], ['query']),
  'listInvoices' : IDL.Func([InvoiceQuery], [IDL.Vec(Invoice)], ['query']),
  'listManagerNotifications' : IDL.Func(
      [NotificationQuery],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'listMyInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'listMyNotifications' : IDL.Func(
      [NotificationQuery],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'listMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'listMyReceipts' : IDL.Func([], [IDL.Vec(Receipt)], ['query']),
  'listPayments' : IDL.Func([PaymentQuery], [IDL.Vec(Payment)], ['query']),
  'listProducts' : IDL.Func([ProductQuery], [IDL.Vec(Product)], ['query']),
  'listProofs' : IDL.Func([ProofQuery], [IDL.Vec(TransferProof)], ['query']),
  'markAllManagerNotificationsRead' : IDL.Func([], [IDL.Nat], []),
  'markAllMyNotificationsRead' : IDL.Func([], [IDL.Nat], []),
  'markManagerNotificationRead' : IDL.Func(
      [NotificationId],
      [IDL.Opt(Notification)],
      [],
    ),
  'markMyNotificationRead' : IDL.Func(
      [NotificationId],
      [IDL.Opt(Notification)],
      [],
    ),
  'recordPayment' : IDL.Func([PaymentInput], [Payment], []),
  'rejectProof' : IDL.Func([ProofId, IDL.Text], [IDL.Opt(TransferProof)], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateCustomer' : IDL.Func(
      [CustomerId, CustomerUpdate],
      [IDL.Opt(Customer)],
      [],
    ),
  'updateProduct' : IDL.Func(
      [ProductId, ProductUpdate],
      [IDL.Opt(Product)],
      [],
    ),
  'updateSettings' : IDL.Func([SettingsInput], [ShopSettings], []),
  'uploadProof' : IDL.Func([ProofInput], [TransferProof], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ProofId = IDL.Nat;
  const ProofStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const InvoiceId = IDL.Nat;
  const Timestamp = IDL.Int;
  const PaymentId = IDL.Nat;
  const CustomerId = IDL.Nat;
  const Satang = IDL.Nat;
  const TransferProof = IDL.Record({
    'id' : ProofId,
    'customerName' : IDL.Text,
    'status' : ProofStatus,
    'note' : IDL.Text,
    'invoiceId' : InvoiceId,
    'reviewNote' : IDL.Text,
    'reviewedAt' : IDL.Opt(Timestamp),
    'imageKey' : IDL.Text,
    'invoiceNumber' : IDL.Text,
    'paymentId' : IDL.Opt(PaymentId),
    'customerId' : CustomerId,
    'transferredAt' : Timestamp,
    'amount' : Satang,
    'uploadedAt' : Timestamp,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Customer = IDL.Record({
    'id' : CustomerId,
    'loginPrincipal' : IDL.Opt(IDL.Principal),
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'creditLimit' : Satang,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CustomerInput = IDL.Record({
    'name' : IDL.Text,
    'creditLimit' : Satang,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const InvoiceLineInput = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const InvoiceInput = IDL.Record({
    'lines' : IDL.Vec(InvoiceLineInput),
    'notes' : IDL.Text,
    'customerId' : CustomerId,
    'issuedAt' : Timestamp,
    'dueAt' : Timestamp,
  });
  const InvoiceStatus = IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'overdue' : IDL.Null,
    'partiallyPaid' : IDL.Null,
  });
  const InvoiceLine = IDL.Record({
    'unit' : IDL.Text,
    'lineTotal' : Satang,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : Satang,
  });
  const Invoice = IDL.Record({
    'id' : InvoiceId,
    'customerName' : IDL.Text,
    'status' : InvoiceStatus,
    'total' : Satang,
    'outstanding' : Satang,
    'lines' : IDL.Vec(InvoiceLine),
    'amountPaid' : Satang,
    'notes' : IDL.Text,
    'number' : IDL.Text,
    'customerId' : CustomerId,
    'issuedAt' : Timestamp,
    'dueAt' : Timestamp,
    'subtotal' : Satang,
  });
  const ProductInput = IDL.Record({
    'sku' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'category' : IDL.Text,
    'unitPrice' : Satang,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'sku' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'category' : IDL.Text,
    'unitPrice' : Satang,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AgingBucket = IDL.Variant({
    'days1to30' : IDL.Null,
    'over90' : IDL.Null,
    'days31to60' : IDL.Null,
    'current' : IDL.Null,
    'days61to90' : IDL.Null,
  });
  const AgingBucketAmount = IDL.Record({
    'bucket' : AgingBucket,
    'amount' : Satang,
  });
  const CustomerDetail = IDL.Record({
    'aging' : IDL.Vec(AgingBucketAmount),
    'customer' : Customer,
    'invoiceCount' : IDL.Nat,
    'outstandingBalance' : Satang,
    'paymentCount' : IDL.Nat,
  });
  const DebtDetail = IDL.Record({
    'customerName' : IDL.Text,
    'aging' : IDL.Vec(AgingBucketAmount),
    'invoices' : IDL.Vec(Invoice),
    'outstandingBalance' : Satang,
    'customerId' : CustomerId,
    'phone' : IDL.Text,
  });
  const DocumentLine = IDL.Record({
    'unit' : IDL.Text,
    'lineTotal' : Satang,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : Satang,
  });
  const DocumentHeader = IDL.Record({
    'taxId' : IDL.Text,
    'address' : IDL.Text,
    'shopName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DebtNoticeDocument = IDL.Record({
    'customerName' : IDL.Text,
    'aging' : IDL.Vec(AgingBucketAmount),
    'customerPhone' : IDL.Text,
    'promptPayRef' : IDL.Text,
    'bankName' : IDL.Text,
    'accountName' : IDL.Text,
    'customerAddress' : IDL.Text,
    'invoices' : IDL.Vec(DocumentLine),
    'outstandingBalance' : Satang,
    'accountNumber' : IDL.Text,
    'issuedAt' : Timestamp,
    'amountInWords' : IDL.Text,
    'header' : DocumentHeader,
  });
  const DebtSummary = IDL.Record({
    'aging' : IDL.Vec(AgingBucketAmount),
    'totalOutstanding' : Satang,
    'customerCount' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'other' : IDL.Null,
    'cash' : IDL.Null,
    'bankTransfer' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : PaymentId,
    'customerName' : IDL.Text,
    'status' : PaymentStatus,
    'method' : PaymentMethod,
    'createdAt' : Timestamp,
    'reference' : IDL.Text,
    'invoiceId' : InvoiceId,
    'invoiceNumber' : IDL.Text,
    'customerId' : CustomerId,
    'amount' : Satang,
    'paidAt' : Timestamp,
    'proofId' : IDL.Opt(ProofId),
  });
  const InvoiceDetail = IDL.Record({
    'proofIds' : IDL.Vec(ProofId),
    'payments' : IDL.Vec(Payment),
    'invoice' : Invoice,
  });
  const InvoiceDocument = IDL.Record({
    'customerName' : IDL.Text,
    'total' : Satang,
    'customerPhone' : IDL.Text,
    'outstanding' : Satang,
    'lines' : IDL.Vec(DocumentLine),
    'amountPaid' : Satang,
    'customerAddress' : IDL.Text,
    'notes' : IDL.Text,
    'number' : IDL.Text,
    'issuedAt' : Timestamp,
    'dueAt' : Timestamp,
    'amountInWords' : IDL.Text,
    'subtotal' : Satang,
    'header' : DocumentHeader,
  });
  const ReceiptId = IDL.Nat;
  const Receipt = IDL.Record({
    'id' : ReceiptId,
    'customerName' : IDL.Text,
    'method' : PaymentMethod,
    'reference' : IDL.Text,
    'invoiceId' : InvoiceId,
    'invoiceNumber' : IDL.Text,
    'number' : IDL.Text,
    'paymentId' : PaymentId,
    'customerId' : CustomerId,
    'issuedAt' : Timestamp,
    'amount' : Satang,
    'paidAt' : Timestamp,
  });
  const ReceiptDocument = IDL.Record({
    'customerName' : IDL.Text,
    'method' : PaymentMethod,
    'reference' : IDL.Text,
    'invoiceNumber' : IDL.Text,
    'customerAddress' : IDL.Text,
    'number' : IDL.Text,
    'issuedAt' : Timestamp,
    'amount' : Satang,
    'amountInWords' : IDL.Text,
    'header' : DocumentHeader,
  });
  const ShopSettings = IDL.Record({
    'taxId' : IDL.Text,
    'defaultPaymentTermsDays' : IDL.Nat,
    'promptPayRef' : IDL.Text,
    'bankName' : IDL.Text,
    'accountName' : IDL.Text,
    'invoicePrefix' : IDL.Text,
    'address' : IDL.Text,
    'shopName' : IDL.Text,
    'accountNumber' : IDL.Text,
    'phone' : IDL.Text,
    'receiptPrefix' : IDL.Text,
  });
  const CustomerQuery = IDL.Record({
    'descending' : IDL.Opt(IDL.Bool),
    'sortBy' : IDL.Opt(IDL.Text),
    'search' : IDL.Opt(IDL.Text),
  });
  const CustomerSummary = IDL.Record({
    'id' : CustomerId,
    'loginPrincipal' : IDL.Opt(IDL.Principal),
    'active' : IDL.Bool,
    'invoiceCount' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'creditLimit' : Satang,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'outstandingBalance' : Satang,
    'phone' : IDL.Text,
  });
  const DebtRow = IDL.Record({
    'customerName' : IDL.Text,
    'aging' : IDL.Vec(AgingBucketAmount),
    'invoiceCount' : IDL.Nat,
    'oldestDueAt' : IDL.Opt(Timestamp),
    'outstandingBalance' : Satang,
    'customerId' : CustomerId,
    'phone' : IDL.Text,
  });
  const InvoiceQuery = IDL.Record({
    'status' : IDL.Opt(InvoiceStatus),
    'search' : IDL.Opt(IDL.Text),
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
    'customerId' : IDL.Opt(CustomerId),
  });
  const NotificationQuery = IDL.Record({
    'limit' : IDL.Opt(IDL.Nat),
    'unreadOnly' : IDL.Opt(IDL.Bool),
  });
  const NotificationId = IDL.Nat;
  const NotificationKind = IDL.Variant({
    'invoiceOverdue' : IDL.Null,
    'paymentRecorded' : IDL.Null,
    'proofApproved' : IDL.Null,
    'proofRejected' : IDL.Null,
    'proofUploaded' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'kind' : NotificationKind,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
  });
  const PaymentQuery = IDL.Record({
    'status' : IDL.Opt(PaymentStatus),
    'search' : IDL.Opt(IDL.Text),
    'customerId' : IDL.Opt(CustomerId),
  });
  const ProductQuery = IDL.Record({
    'search' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'activeOnly' : IDL.Opt(IDL.Bool),
  });
  const ProofQuery = IDL.Record({
    'status' : IDL.Opt(ProofStatus),
    'customerId' : IDL.Opt(CustomerId),
  });
  const PaymentInput = IDL.Record({
    'method' : PaymentMethod,
    'reference' : IDL.Text,
    'invoiceId' : InvoiceId,
    'amount' : Satang,
    'paidAt' : Timestamp,
  });
  const CustomerUpdate = IDL.Record({
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'creditLimit' : Satang,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProductUpdate = IDL.Record({
    'sku' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'category' : IDL.Text,
    'unitPrice' : Satang,
  });
  const SettingsInput = IDL.Record({
    'taxId' : IDL.Text,
    'defaultPaymentTermsDays' : IDL.Nat,
    'promptPayRef' : IDL.Text,
    'bankName' : IDL.Text,
    'accountName' : IDL.Text,
    'invoicePrefix' : IDL.Text,
    'address' : IDL.Text,
    'shopName' : IDL.Text,
    'accountNumber' : IDL.Text,
    'phone' : IDL.Text,
    'receiptPrefix' : IDL.Text,
  });
  const ProofInput = IDL.Record({
    'note' : IDL.Text,
    'invoiceId' : InvoiceId,
    'imageKey' : IDL.Text,
    'transferredAt' : Timestamp,
    'amount' : Satang,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'approveProof' : IDL.Func([ProofId], [IDL.Opt(TransferProof)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bindCustomerLogin' : IDL.Func(
        [CustomerId, IDL.Principal],
        [IDL.Opt(Customer)],
        [],
      ),
    'claimCustomerAccount' : IDL.Func([CustomerId], [IDL.Opt(Customer)], []),
    'countUnreadManagerNotifications' : IDL.Func([], [IDL.Nat], ['query']),
    'countUnreadMyNotifications' : IDL.Func([], [IDL.Nat], ['query']),
    'createCustomer' : IDL.Func([CustomerInput], [Customer], []),
    'createInvoice' : IDL.Func([InvoiceInput], [Invoice], []),
    'createProduct' : IDL.Func([ProductInput], [Product], []),
    'deactivateProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func(
        [CustomerId],
        [IDL.Opt(CustomerDetail)],
        ['query'],
      ),
    'getCustomerDebt' : IDL.Func(
        [CustomerId],
        [IDL.Opt(DebtDetail)],
        ['query'],
      ),
    'getDebtNoticeDocument' : IDL.Func(
        [CustomerId],
        [IDL.Opt(DebtNoticeDocument)],
        ['query'],
      ),
    'getDebtSummary' : IDL.Func([], [DebtSummary], ['query']),
    'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(InvoiceDetail)], ['query']),
    'getInvoiceDocument' : IDL.Func(
        [InvoiceId],
        [IDL.Opt(InvoiceDocument)],
        ['query'],
      ),
    'getMyCustomer' : IDL.Func([], [IDL.Opt(Customer)], ['query']),
    'getMyDebt' : IDL.Func([], [IDL.Opt(DebtDetail)], ['query']),
    'getMyInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
    'getMyReceipt' : IDL.Func([ReceiptId], [IDL.Opt(Receipt)], ['query']),
    'getPayment' : IDL.Func([PaymentId], [IDL.Opt(Payment)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProof' : IDL.Func([ProofId], [IDL.Opt(TransferProof)], ['query']),
    'getReceiptDocument' : IDL.Func(
        [ReceiptId],
        [IDL.Opt(ReceiptDocument)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [ShopSettings], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCustomers' : IDL.Func(
        [CustomerQuery],
        [IDL.Vec(CustomerSummary)],
        ['query'],
      ),
    'listDebts' : IDL.Func([], [IDL.Vec(DebtRow)], ['query']),
    'listInvoices' : IDL.Func([InvoiceQuery], [IDL.Vec(Invoice)], ['query']),
    'listManagerNotifications' : IDL.Func(
        [NotificationQuery],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'listMyInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'listMyNotifications' : IDL.Func(
        [NotificationQuery],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'listMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'listMyReceipts' : IDL.Func([], [IDL.Vec(Receipt)], ['query']),
    'listPayments' : IDL.Func([PaymentQuery], [IDL.Vec(Payment)], ['query']),
    'listProducts' : IDL.Func([ProductQuery], [IDL.Vec(Product)], ['query']),
    'listProofs' : IDL.Func([ProofQuery], [IDL.Vec(TransferProof)], ['query']),
    'markAllManagerNotificationsRead' : IDL.Func([], [IDL.Nat], []),
    'markAllMyNotificationsRead' : IDL.Func([], [IDL.Nat], []),
    'markManagerNotificationRead' : IDL.Func(
        [NotificationId],
        [IDL.Opt(Notification)],
        [],
      ),
    'markMyNotificationRead' : IDL.Func(
        [NotificationId],
        [IDL.Opt(Notification)],
        [],
      ),
    'recordPayment' : IDL.Func([PaymentInput], [Payment], []),
    'rejectProof' : IDL.Func([ProofId, IDL.Text], [IDL.Opt(TransferProof)], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateCustomer' : IDL.Func(
        [CustomerId, CustomerUpdate],
        [IDL.Opt(Customer)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, ProductUpdate],
        [IDL.Opt(Product)],
        [],
      ),
    'updateSettings' : IDL.Func([SettingsInput], [ShopSettings], []),
    'uploadProof' : IDL.Func([ProofInput], [TransferProof], []),
  });
};

export const init = ({ IDL }) => { return []; };