/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AgingBucketAmount {
    bucket: AgingBucket;
    amount: Satang;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface Customer {
    id: CustomerId;
    loginPrincipal?: Principal;
    active: boolean;
    name: string;
    createdAt: Timestamp;
    creditLimit: Satang;
    address: string;
    notes: string;
    phone: string;
}
export interface CustomerDetail {
    aging: Array<AgingBucketAmount>;
    customer: Customer;
    invoiceCount: bigint;
    outstandingBalance: Satang;
    paymentCount: bigint;
}
export type CustomerId = bigint;
export interface CustomerInput {
    name: string;
    creditLimit: Satang;
    address: string;
    notes: string;
    phone: string;
}
export interface CustomerQuery {
    descending?: boolean;
    sortBy?: string;
    search?: string;
}
export interface CustomerSummary {
    id: CustomerId;
    loginPrincipal?: Principal;
    active: boolean;
    invoiceCount: bigint;
    name: string;
    createdAt: Timestamp;
    creditLimit: Satang;
    address: string;
    notes: string;
    outstandingBalance: Satang;
    phone: string;
}
export interface CustomerUpdate {
    active: boolean;
    name: string;
    creditLimit: Satang;
    address: string;
    notes: string;
    phone: string;
}
export interface DebtDetail {
    customerName: string;
    aging: Array<AgingBucketAmount>;
    invoices: Array<Invoice>;
    outstandingBalance: Satang;
    customerId: CustomerId;
    phone: string;
}
export interface DebtNoticeDocument {
    customerName: string;
    aging: Array<AgingBucketAmount>;
    customerPhone: string;
    promptPayRef: string;
    bankName: string;
    accountName: string;
    customerAddress: string;
    invoices: Array<DocumentLine>;
    outstandingBalance: Satang;
    accountNumber: string;
    issuedAt: Timestamp;
    amountInWords: string;
    header: DocumentHeader;
}
export interface DebtRow {
    customerName: string;
    aging: Array<AgingBucketAmount>;
    invoiceCount: bigint;
    oldestDueAt?: Timestamp;
    outstandingBalance: Satang;
    customerId: CustomerId;
    phone: string;
}
export interface DebtSummary {
    aging: Array<AgingBucketAmount>;
    totalOutstanding: Satang;
    customerCount: bigint;
}
export interface DocumentHeader {
    taxId: string;
    address: string;
    shopName: string;
    phone: string;
}
export interface DocumentLine {
    unit: string;
    lineTotal: Satang;
    description: string;
    quantity: bigint;
    unitPrice: Satang;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Invoice {
    id: InvoiceId;
    customerName: string;
    status: InvoiceStatus;
    total: Satang;
    outstanding: Satang;
    lines: Array<InvoiceLine>;
    amountPaid: Satang;
    notes: string;
    number: string;
    customerId: CustomerId;
    issuedAt: Timestamp;
    dueAt: Timestamp;
    subtotal: Satang;
}
export interface InvoiceDetail {
    proofIds: Array<ProofId>;
    payments: Array<Payment>;
    invoice: Invoice;
}
export interface InvoiceDocument {
    customerName: string;
    total: Satang;
    customerPhone: string;
    outstanding: Satang;
    lines: Array<DocumentLine>;
    amountPaid: Satang;
    customerAddress: string;
    notes: string;
    number: string;
    issuedAt: Timestamp;
    dueAt: Timestamp;
    amountInWords: string;
    subtotal: Satang;
    header: DocumentHeader;
}
export type InvoiceId = bigint;
export interface InvoiceInput {
    lines: Array<InvoiceLineInput>;
    notes: string;
    customerId: CustomerId;
    issuedAt: Timestamp;
    dueAt: Timestamp;
}
export interface InvoiceLine {
    unit: string;
    lineTotal: Satang;
    productId: ProductId;
    productName: string;
    quantity: bigint;
    unitPrice: Satang;
}
export interface InvoiceLineInput {
    productId: ProductId;
    quantity: bigint;
}
export interface InvoiceQuery {
    status?: InvoiceStatus;
    search?: string;
    toDate?: Timestamp;
    fromDate?: Timestamp;
    customerId?: CustomerId;
}
export interface Notification {
    id: NotificationId;
    title: string;
    body: string;
    kind: NotificationKind;
    createdAt: Timestamp;
    read: boolean;
}
export type NotificationId = bigint;
export interface NotificationQuery {
    limit?: bigint;
    unreadOnly?: boolean;
}
export interface Payment {
    id: PaymentId;
    customerName: string;
    status: PaymentStatus;
    method: PaymentMethod;
    createdAt: Timestamp;
    reference: string;
    invoiceId: InvoiceId;
    invoiceNumber: string;
    customerId: CustomerId;
    amount: Satang;
    paidAt: Timestamp;
    proofId?: ProofId;
}
export type PaymentId = bigint;
export interface PaymentInput {
    method: PaymentMethod;
    reference: string;
    invoiceId: InvoiceId;
    amount: Satang;
    paidAt: Timestamp;
}
export interface PaymentQuery {
    status?: PaymentStatus;
    search?: string;
    customerId?: CustomerId;
}
export interface Product {
    id: ProductId;
    sku: string;
    active: boolean;
    name: string;
    createdAt: Timestamp;
    unit: string;
    category: string;
    unitPrice: Satang;
}
export type ProductId = bigint;
export interface ProductInput {
    sku: string;
    name: string;
    unit: string;
    category: string;
    unitPrice: Satang;
}
export interface ProductQuery {
    search?: string;
    category?: string;
    activeOnly?: boolean;
}
export interface ProductUpdate {
    sku: string;
    active: boolean;
    name: string;
    unit: string;
    category: string;
    unitPrice: Satang;
}
export type ProofId = bigint;
export interface ProofInput {
    note: string;
    invoiceId: InvoiceId;
    imageKey: string;
    transferredAt: Timestamp;
    amount: Satang;
}
export interface ProofQuery {
    status?: ProofStatus;
    customerId?: CustomerId;
}
export interface Receipt {
    id: ReceiptId;
    customerName: string;
    method: PaymentMethod;
    reference: string;
    invoiceId: InvoiceId;
    invoiceNumber: string;
    number: string;
    paymentId: PaymentId;
    customerId: CustomerId;
    issuedAt: Timestamp;
    amount: Satang;
    paidAt: Timestamp;
}
export interface ReceiptDocument {
    customerName: string;
    method: PaymentMethod;
    reference: string;
    invoiceNumber: string;
    customerAddress: string;
    number: string;
    issuedAt: Timestamp;
    amount: Satang;
    amountInWords: string;
    header: DocumentHeader;
}
export type ReceiptId = bigint;
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Satang = bigint;
export interface SettingsInput {
    taxId: string;
    defaultPaymentTermsDays: bigint;
    promptPayRef: string;
    bankName: string;
    accountName: string;
    invoicePrefix: string;
    address: string;
    shopName: string;
    accountNumber: string;
    phone: string;
    receiptPrefix: string;
}
export interface ShopSettings {
    taxId: string;
    defaultPaymentTermsDays: bigint;
    promptPayRef: string;
    bankName: string;
    accountName: string;
    invoicePrefix: string;
    address: string;
    shopName: string;
    accountNumber: string;
    phone: string;
    receiptPrefix: string;
}
export type Timestamp = bigint;
export interface TransferProof {
    id: ProofId;
    customerName: string;
    status: ProofStatus;
    note: string;
    invoiceId: InvoiceId;
    reviewNote: string;
    reviewedAt?: Timestamp;
    imageKey: string;
    invoiceNumber: string;
    paymentId?: PaymentId;
    customerId: CustomerId;
    transferredAt: Timestamp;
    amount: Satang;
    uploadedAt: Timestamp;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum AgingBucket {
    days1to30 = "days1to30",
    over90 = "over90",
    days31to60 = "days31to60",
    current = "current",
    days61to90 = "days61to90"
}
export enum InvoiceStatus {
    paid = "paid",
    unpaid = "unpaid",
    overdue = "overdue",
    partiallyPaid = "partiallyPaid"
}
export enum NotificationKind {
    invoiceOverdue = "invoiceOverdue",
    paymentRecorded = "paymentRecorded",
    proofApproved = "proofApproved",
    proofRejected = "proofRejected",
    proofUploaded = "proofUploaded"
}
export enum PaymentMethod {
    other = "other",
    cash = "cash",
    bankTransfer = "bankTransfer"
}
export enum PaymentStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ProofStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Approve a proof, creating the linked payment.
     */
    approveProof(id: ProofId): Promise<TransferProof | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Bind a login principal to a customer account (manager only).
     */
    bindCustomerLogin(id: CustomerId, principal: Principal): Promise<Customer | null>;
    /**
     * / Bind the signed-in caller's own principal to an unclaimed customer account.
     */
    claimCustomerAccount(id: CustomerId): Promise<Customer | null>;
    /**
     * / Count unread manager notifications.
     */
    countUnreadManagerNotifications(): Promise<bigint>;
    /**
     * / Count unread notifications for the signed-in customer.
     */
    countUnreadMyNotifications(): Promise<bigint>;
    /**
     * / Create a customer account with a provisioned login.
     */
    createCustomer(input: CustomerInput): Promise<Customer>;
    /**
     * / Create an invoice for a customer.
     */
    createInvoice(input: InvoiceInput): Promise<Invoice>;
    /**
     * / Create a product.
     */
    createProduct(input: ProductInput): Promise<Product>;
    /**
     * / Deactivate a product without deleting its invoice history.
     */
    deactivateProduct(id: ProductId): Promise<Product | null>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Return the API documentation as Markdown.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Fetch a customer detail view.
     */
    getCustomer(id: CustomerId): Promise<CustomerDetail | null>;
    /**
     * / Fetch one customer's debt detail.
     */
    getCustomerDebt(customerId: CustomerId): Promise<DebtDetail | null>;
    /**
     * / Build the printable debt notice document for a customer.
     */
    getDebtNoticeDocument(customerId: CustomerId): Promise<DebtNoticeDocument | null>;
    /**
     * / Aggregate outstanding balance and aging across all customers.
     */
    getDebtSummary(): Promise<DebtSummary>;
    /**
     * / Fetch an invoice detail view.
     */
    getInvoice(id: InvoiceId): Promise<InvoiceDetail | null>;
    /**
     * / Build the printable invoice document for an invoice.
     */
    getInvoiceDocument(id: InvoiceId): Promise<InvoiceDocument | null>;
    /**
     * / Resolve the signed-in caller's own customer account.
     */
    getMyCustomer(): Promise<Customer | null>;
    /**
     * / Fetch the signed-in customer's own debt detail.
     */
    getMyDebt(): Promise<DebtDetail | null>;
    /**
     * / Fetch one of the signed-in customer's own invoices.
     */
    getMyInvoice(id: InvoiceId): Promise<Invoice | null>;
    /**
     * / Fetch one of the signed-in customer's own receipts.
     */
    getMyReceipt(id: ReceiptId): Promise<Receipt | null>;
    /**
     * / Fetch a single payment.
     */
    getPayment(id: PaymentId): Promise<Payment | null>;
    /**
     * / Fetch a single product.
     */
    getProduct(id: ProductId): Promise<Product | null>;
    /**
     * / Fetch a single transfer proof.
     */
    getProof(id: ProofId): Promise<TransferProof | null>;
    /**
     * / Build the printable receipt document for a receipt.
     */
    getReceiptDocument(id: ReceiptId): Promise<ReceiptDocument | null>;
    /**
     * / Read the shop profile and bank details.
     */
    getSettings(): Promise<ShopSettings>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List customers with search and sort applied.
     */
    listCustomers(filter: CustomerQuery): Promise<Array<CustomerSummary>>;
    /**
     * / List every customer with an outstanding balance.
     */
    listDebts(): Promise<Array<DebtRow>>;
    /**
     * / List invoices with search, status, and date-range filters applied.
     */
    listInvoices(filter: InvoiceQuery): Promise<Array<Invoice>>;
    /**
     * / List notifications for the manager.
     */
    listManagerNotifications(filter: NotificationQuery): Promise<Array<Notification>>;
    /**
     * / List the signed-in customer's own invoices.
     */
    listMyInvoices(): Promise<Array<Invoice>>;
    /**
     * / List notifications for the signed-in customer.
     */
    listMyNotifications(filter: NotificationQuery): Promise<Array<Notification>>;
    /**
     * / List the signed-in customer's own payments.
     */
    listMyPayments(): Promise<Array<Payment>>;
    /**
     * / List the signed-in customer's own receipts.
     */
    listMyReceipts(): Promise<Array<Receipt>>;
    /**
     * / List payments with search and status filter applied.
     */
    listPayments(filter: PaymentQuery): Promise<Array<Payment>>;
    /**
     * / List products with search and category filter applied.
     */
    listProducts(filter: ProductQuery): Promise<Array<Product>>;
    /**
     * / List transfer proofs awaiting or already reviewed.
     */
    listProofs(filter: ProofQuery): Promise<Array<TransferProof>>;
    /**
     * / Mark every manager notification as read.
     */
    markAllManagerNotificationsRead(): Promise<bigint>;
    /**
     * / Mark every notification of the signed-in customer as read.
     */
    markAllMyNotificationsRead(): Promise<bigint>;
    /**
     * / Mark one manager notification as read.
     */
    markManagerNotificationRead(id: NotificationId): Promise<Notification | null>;
    /**
     * / Mark one of the signed-in customer's notifications as read.
     */
    markMyNotificationRead(id: NotificationId): Promise<Notification | null>;
    /**
     * / Record a manual payment against an invoice.
     */
    recordPayment(input: PaymentInput): Promise<Payment>;
    /**
     * / Reject a proof, leaving the invoice balance unchanged.
     */
    rejectProof(id: ProofId, note: string): Promise<TransferProof | null>;
    schema(): Promise<string>;
    /**
     * / Edit an existing customer account.
     */
    updateCustomer(id: CustomerId, input: CustomerUpdate): Promise<Customer | null>;
    /**
     * / Edit an existing product.
     */
    updateProduct(id: ProductId, input: ProductUpdate): Promise<Product | null>;
    /**
     * / Update the shop profile, bank details, and numbering settings.
     */
    updateSettings(input: SettingsInput): Promise<ShopSettings>;
    /**
     * / Upload a bank-transfer proof against an invoice.
     */
    uploadProof(input: ProofInput): Promise<TransferProof>;
}
import type { AgingBucket as _AgingBucket, AgingBucketAmount as _AgingBucketAmount, Cell as _Cell, Customer as _Customer, CustomerDetail as _CustomerDetail, CustomerId as _CustomerId, CustomerQuery as _CustomerQuery, CustomerSummary as _CustomerSummary, DebtDetail as _DebtDetail, DebtNoticeDocument as _DebtNoticeDocument, DebtRow as _DebtRow, DebtSummary as _DebtSummary, DocumentHeader as _DocumentHeader, DocumentLine as _DocumentLine, Error as _Error, Invoice as _Invoice, InvoiceDetail as _InvoiceDetail, InvoiceDocument as _InvoiceDocument, InvoiceId as _InvoiceId, InvoiceLine as _InvoiceLine, InvoiceQuery as _InvoiceQuery, InvoiceStatus as _InvoiceStatus, Notification as _Notification, NotificationId as _NotificationId, NotificationKind as _NotificationKind, NotificationQuery as _NotificationQuery, Payment as _Payment, PaymentId as _PaymentId, PaymentInput as _PaymentInput, PaymentMethod as _PaymentMethod, PaymentQuery as _PaymentQuery, PaymentStatus as _PaymentStatus, Product as _Product, ProductQuery as _ProductQuery, ProofId as _ProofId, ProofQuery as _ProofQuery, ProofStatus as _ProofStatus, Receipt as _Receipt, ReceiptDocument as _ReceiptDocument, ReceiptId as _ReceiptId, Result as _Result, Result__1 as _Result__1, Satang as _Satang, Timestamp as _Timestamp, TransferProof as _TransferProof, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async approveProof(arg0: ProofId): Promise<TransferProof | null> {
        if (this.processError) {
            try {
                const result = await this.actor.approveProof(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveProof(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bindCustomerLogin(arg0: CustomerId, arg1: Principal): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.bindCustomerLogin(arg0, arg1);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bindCustomerLogin(arg0, arg1);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimCustomerAccount(arg0: CustomerId): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.claimCustomerAccount(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimCustomerAccount(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async countUnreadManagerNotifications(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.countUnreadManagerNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countUnreadManagerNotifications();
            return result;
        }
    }
    async countUnreadMyNotifications(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.countUnreadMyNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countUnreadMyNotifications();
            return result;
        }
    }
    async createCustomer(arg0: CustomerInput): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(arg0);
                return from_candid_Customer_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(arg0);
            return from_candid_Customer_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInvoice(arg0: InvoiceInput): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0);
                return from_candid_Invoice_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0);
            return from_candid_Invoice_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0);
            return result;
        }
    }
    async deactivateProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateProduct(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateProduct(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: CustomerId): Promise<CustomerDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerDebt(arg0: CustomerId): Promise<DebtDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerDebt(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerDebt(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDebtNoticeDocument(arg0: CustomerId): Promise<DebtNoticeDocument | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDebtNoticeDocument(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDebtNoticeDocument(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDebtSummary(): Promise<DebtSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDebtSummary();
                return from_candid_DebtSummary_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDebtSummary();
            return from_candid_DebtSummary_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: InvoiceId): Promise<InvoiceDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoiceDocument(arg0: InvoiceId): Promise<InvoiceDocument | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoiceDocument(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoiceDocument(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCustomer(): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCustomer();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCustomer();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDebt(): Promise<DebtDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDebt();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDebt();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInvoice(arg0: InvoiceId): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInvoice(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInvoice(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReceipt(arg0: ReceiptId): Promise<Receipt | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReceipt(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReceipt(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: PaymentId): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProof(arg0: ProofId): Promise<TransferProof | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProof(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProof(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceiptDocument(arg0: ReceiptId): Promise<ReceiptDocument | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceiptDocument(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceiptDocument(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<ShopSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCustomers(arg0: CustomerQuery): Promise<Array<CustomerSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomers(to_candid_CustomerQuery_n63(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomers(to_candid_CustomerQuery_n63(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDebts(): Promise<Array<DebtRow>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDebts();
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDebts();
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInvoices(arg0: InvoiceQuery): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoices(to_candid_InvoiceQuery_n71(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoices(to_candid_InvoiceQuery_n71(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listManagerNotifications(arg0: NotificationQuery): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.listManagerNotifications(to_candid_NotificationQuery_n74(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listManagerNotifications(to_candid_NotificationQuery_n74(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyInvoices();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyInvoices();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyNotifications(arg0: NotificationQuery): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyNotifications(to_candid_NotificationQuery_n74(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyNotifications(to_candid_NotificationQuery_n74(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyPayments();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyPayments();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyReceipts(): Promise<Array<Receipt>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyReceipts();
                return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyReceipts();
            return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPayments(arg0: PaymentQuery): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPayments(to_candid_PaymentQuery_n81(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPayments(to_candid_PaymentQuery_n81(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(arg0: ProductQuery): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_ProductQuery_n84(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_ProductQuery_n84(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async listProofs(arg0: ProofQuery): Promise<Array<TransferProof>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProofs(to_candid_ProofQuery_n86(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n89(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProofs(to_candid_ProofQuery_n86(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n89(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllManagerNotificationsRead(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllManagerNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllManagerNotificationsRead();
            return result;
        }
    }
    async markAllMyNotificationsRead(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllMyNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllMyNotificationsRead();
            return result;
        }
    }
    async markManagerNotificationRead(arg0: NotificationId): Promise<Notification | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markManagerNotificationRead(arg0);
                return from_candid_opt_n90(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markManagerNotificationRead(arg0);
            return from_candid_opt_n90(this._uploadFile, this._downloadFile, result);
        }
    }
    async markMyNotificationRead(arg0: NotificationId): Promise<Notification | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markMyNotificationRead(arg0);
                return from_candid_opt_n90(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMyNotificationRead(arg0);
            return from_candid_opt_n90(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordPayment(arg0: PaymentInput): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(to_candid_PaymentInput_n91(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Payment_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(to_candid_PaymentInput_n91(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Payment_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectProof(arg0: ProofId, arg1: string): Promise<TransferProof | null> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectProof(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectProof(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async updateCustomer(arg0: CustomerId, arg1: CustomerUpdate): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: ProductId, arg1: ProductUpdate): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: SettingsInput): Promise<ShopSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
    async uploadProof(arg0: ProofInput): Promise<TransferProof> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProof(arg0);
                return from_candid_TransferProof_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProof(arg0);
            return from_candid_TransferProof_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AgingBucketAmount_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgingBucketAmount): AgingBucketAmount {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_AgingBucket_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgingBucket): AgingBucket {
    return "days1to30" in value ? AgingBucket.days1to30 : "over90" in value ? AgingBucket.over90 : "days31to60" in value ? AgingBucket.days31to60 : "current" in value ? AgingBucket.current : "days61to90" in value ? AgingBucket.days61to90 : value;
}
function from_candid_Cell_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerDetail_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerDetail): CustomerDetail {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerSummary_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerSummary): CustomerSummary {
    return from_candid_record_n67(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_DebtDetail_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DebtDetail): DebtDetail {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_DebtNoticeDocument_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DebtNoticeDocument): DebtNoticeDocument {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_DebtRow_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DebtRow): DebtRow {
    return from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_DebtSummary_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DebtSummary): DebtSummary {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceDetail_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceDetail): InvoiceDetail {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return "paid" in value ? InvoiceStatus.paid : "unpaid" in value ? InvoiceStatus.unpaid : "overdue" in value ? InvoiceStatus.overdue : "partiallyPaid" in value ? InvoiceStatus.partiallyPaid : value;
}
function from_candid_Invoice_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationKind_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationKind): NotificationKind {
    return "invoiceOverdue" in value ? NotificationKind.invoiceOverdue : "paymentRecorded" in value ? NotificationKind.paymentRecorded : "proofApproved" in value ? NotificationKind.proofApproved : "proofRejected" in value ? NotificationKind.proofRejected : "proofUploaded" in value ? NotificationKind.proofUploaded : value;
}
function from_candid_Notification_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n78(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return "other" in value ? PaymentMethod.other : "cash" in value ? PaymentMethod.cash : "bankTransfer" in value ? PaymentMethod.bankTransfer : value;
}
function from_candid_PaymentStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "approved" in value ? PaymentStatus.approved : "rejected" in value ? PaymentStatus.rejected : value;
}
function from_candid_Payment_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_ProofStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProofStatus): ProofStatus {
    return "pending" in value ? ProofStatus.pending : "approved" in value ? ProofStatus.approved : "rejected" in value ? ProofStatus.rejected : value;
}
function from_candid_ReceiptDocument_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReceiptDocument): ReceiptDocument {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Receipt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Receipt): Receipt {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TransferProof_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferProof): TransferProof {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentId]): PaymentId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerDetail]): CustomerDetail | null {
    return value.length === 0 ? null : from_candid_CustomerDetail_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DebtDetail]): DebtDetail | null {
    return value.length === 0 ? null : from_candid_DebtDetail_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DebtNoticeDocument]): DebtNoticeDocument | null {
    return value.length === 0 ? null : from_candid_DebtNoticeDocument_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvoiceDetail]): InvoiceDetail | null {
    return value.length === 0 ? null : from_candid_InvoiceDetail_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransferProof]): TransferProof | null {
    return value.length === 0 ? null : from_candid_TransferProof_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProofId]): ProofId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvoiceDocument]): InvoiceDocument | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Receipt]): Receipt | null {
    return value.length === 0 ? null : from_candid_Receipt_n57(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : from_candid_Payment_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReceiptDocument]): ReceiptDocument | null {
    return value.length === 0 ? null : from_candid_ReceiptDocument_n61(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Notification]): Notification | null {
    return value.length === 0 ? null : from_candid_Notification_n77(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CustomerId;
    loginPrincipal: [] | [Principal];
    active: boolean;
    name: string;
    createdAt: _Timestamp;
    creditLimit: _Satang;
    address: string;
    notes: string;
    phone: string;
}): {
    id: CustomerId;
    loginPrincipal?: Principal;
    active: boolean;
    name: string;
    createdAt: Timestamp;
    creditLimit: Satang;
    address: string;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        loginPrincipal: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.loginPrincipal)),
        active: value.active,
        name: value.name,
        createdAt: value.createdAt,
        creditLimit: value.creditLimit,
        address: value.address,
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InvoiceId;
    customerName: string;
    status: _InvoiceStatus;
    total: _Satang;
    outstanding: _Satang;
    lines: Array<_InvoiceLine>;
    amountPaid: _Satang;
    notes: string;
    number: string;
    customerId: _CustomerId;
    issuedAt: _Timestamp;
    dueAt: _Timestamp;
    subtotal: _Satang;
}): {
    id: InvoiceId;
    customerName: string;
    status: InvoiceStatus;
    total: Satang;
    outstanding: Satang;
    lines: Array<InvoiceLine>;
    amountPaid: Satang;
    notes: string;
    number: string;
    customerId: CustomerId;
    issuedAt: Timestamp;
    dueAt: Timestamp;
    subtotal: Satang;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_InvoiceStatus_n18(_uploadFile, _downloadFile, value.status),
        total: value.total,
        outstanding: value.outstanding,
        lines: value.lines,
        amountPaid: value.amountPaid,
        notes: value.notes,
        number: value.number,
        customerId: value.customerId,
        issuedAt: value.issuedAt,
        dueAt: value.dueAt,
        subtotal: value.subtotal
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n22(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n26(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aging: Array<_AgingBucketAmount>;
    customer: _Customer;
    invoiceCount: bigint;
    outstandingBalance: _Satang;
    paymentCount: bigint;
}): {
    aging: Array<AgingBucketAmount>;
    customer: Customer;
    invoiceCount: bigint;
    outstandingBalance: Satang;
    paymentCount: bigint;
} {
    return {
        aging: from_candid_vec_n32(_uploadFile, _downloadFile, value.aging),
        customer: from_candid_Customer_n13(_uploadFile, _downloadFile, value.customer),
        invoiceCount: value.invoiceCount,
        outstandingBalance: value.outstandingBalance,
        paymentCount: value.paymentCount
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bucket: _AgingBucket;
    amount: _Satang;
}): {
    bucket: AgingBucket;
    amount: Satang;
} {
    return {
        bucket: from_candid_AgingBucket_n35(_uploadFile, _downloadFile, value.bucket),
        amount: value.amount
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    aging: Array<_AgingBucketAmount>;
    invoices: Array<_Invoice>;
    outstandingBalance: _Satang;
    customerId: _CustomerId;
    phone: string;
}): {
    customerName: string;
    aging: Array<AgingBucketAmount>;
    invoices: Array<Invoice>;
    outstandingBalance: Satang;
    customerId: CustomerId;
    phone: string;
} {
    return {
        customerName: value.customerName,
        aging: from_candid_vec_n32(_uploadFile, _downloadFile, value.aging),
        invoices: from_candid_vec_n39(_uploadFile, _downloadFile, value.invoices),
        outstandingBalance: value.outstandingBalance,
        customerId: value.customerId,
        phone: value.phone
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    aging: Array<_AgingBucketAmount>;
    customerPhone: string;
    promptPayRef: string;
    bankName: string;
    accountName: string;
    customerAddress: string;
    invoices: Array<_DocumentLine>;
    outstandingBalance: _Satang;
    accountNumber: string;
    issuedAt: _Timestamp;
    amountInWords: string;
    header: _DocumentHeader;
}): {
    customerName: string;
    aging: Array<AgingBucketAmount>;
    customerPhone: string;
    promptPayRef: string;
    bankName: string;
    accountName: string;
    customerAddress: string;
    invoices: Array<DocumentLine>;
    outstandingBalance: Satang;
    accountNumber: string;
    issuedAt: Timestamp;
    amountInWords: string;
    header: DocumentHeader;
} {
    return {
        customerName: value.customerName,
        aging: from_candid_vec_n32(_uploadFile, _downloadFile, value.aging),
        customerPhone: value.customerPhone,
        promptPayRef: value.promptPayRef,
        bankName: value.bankName,
        accountName: value.accountName,
        customerAddress: value.customerAddress,
        invoices: value.invoices,
        outstandingBalance: value.outstandingBalance,
        accountNumber: value.accountNumber,
        issuedAt: value.issuedAt,
        amountInWords: value.amountInWords,
        header: value.header
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aging: Array<_AgingBucketAmount>;
    totalOutstanding: _Satang;
    customerCount: bigint;
}): {
    aging: Array<AgingBucketAmount>;
    totalOutstanding: Satang;
    customerCount: bigint;
} {
    return {
        aging: from_candid_vec_n32(_uploadFile, _downloadFile, value.aging),
        totalOutstanding: value.totalOutstanding,
        customerCount: value.customerCount
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proofIds: Array<_ProofId>;
    payments: Array<_Payment>;
    invoice: _Invoice;
}): {
    proofIds: Array<ProofId>;
    payments: Array<Payment>;
    invoice: Invoice;
} {
    return {
        proofIds: value.proofIds,
        payments: from_candid_vec_n48(_uploadFile, _downloadFile, value.payments),
        invoice: from_candid_Invoice_n16(_uploadFile, _downloadFile, value.invoice)
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentId;
    customerName: string;
    status: _PaymentStatus;
    method: _PaymentMethod;
    createdAt: _Timestamp;
    reference: string;
    invoiceId: _InvoiceId;
    invoiceNumber: string;
    customerId: _CustomerId;
    amount: _Satang;
    paidAt: _Timestamp;
    proofId: [] | [_ProofId];
}): {
    id: PaymentId;
    customerName: string;
    status: PaymentStatus;
    method: PaymentMethod;
    createdAt: Timestamp;
    reference: string;
    invoiceId: InvoiceId;
    invoiceNumber: string;
    customerId: CustomerId;
    amount: Satang;
    paidAt: Timestamp;
    proofId?: ProofId;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_PaymentStatus_n51(_uploadFile, _downloadFile, value.status),
        method: from_candid_PaymentMethod_n52(_uploadFile, _downloadFile, value.method),
        createdAt: value.createdAt,
        reference: value.reference,
        invoiceId: value.invoiceId,
        invoiceNumber: value.invoiceNumber,
        customerId: value.customerId,
        amount: value.amount,
        paidAt: value.paidAt,
        proofId: record_opt_to_undefined(from_candid_opt_n53(_uploadFile, _downloadFile, value.proofId))
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReceiptId;
    customerName: string;
    method: _PaymentMethod;
    reference: string;
    invoiceId: _InvoiceId;
    invoiceNumber: string;
    number: string;
    paymentId: _PaymentId;
    customerId: _CustomerId;
    issuedAt: _Timestamp;
    amount: _Satang;
    paidAt: _Timestamp;
}): {
    id: ReceiptId;
    customerName: string;
    method: PaymentMethod;
    reference: string;
    invoiceId: InvoiceId;
    invoiceNumber: string;
    number: string;
    paymentId: PaymentId;
    customerId: CustomerId;
    issuedAt: Timestamp;
    amount: Satang;
    paidAt: Timestamp;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        method: from_candid_PaymentMethod_n52(_uploadFile, _downloadFile, value.method),
        reference: value.reference,
        invoiceId: value.invoiceId,
        invoiceNumber: value.invoiceNumber,
        number: value.number,
        paymentId: value.paymentId,
        customerId: value.customerId,
        issuedAt: value.issuedAt,
        amount: value.amount,
        paidAt: value.paidAt
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    method: _PaymentMethod;
    reference: string;
    invoiceNumber: string;
    customerAddress: string;
    number: string;
    issuedAt: _Timestamp;
    amount: _Satang;
    amountInWords: string;
    header: _DocumentHeader;
}): {
    customerName: string;
    method: PaymentMethod;
    reference: string;
    invoiceNumber: string;
    customerAddress: string;
    number: string;
    issuedAt: Timestamp;
    amount: Satang;
    amountInWords: string;
    header: DocumentHeader;
} {
    return {
        customerName: value.customerName,
        method: from_candid_PaymentMethod_n52(_uploadFile, _downloadFile, value.method),
        reference: value.reference,
        invoiceNumber: value.invoiceNumber,
        customerAddress: value.customerAddress,
        number: value.number,
        issuedAt: value.issuedAt,
        amount: value.amount,
        amountInWords: value.amountInWords,
        header: value.header
    };
}
function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CustomerId;
    loginPrincipal: [] | [Principal];
    active: boolean;
    invoiceCount: bigint;
    name: string;
    createdAt: _Timestamp;
    creditLimit: _Satang;
    address: string;
    notes: string;
    outstandingBalance: _Satang;
    phone: string;
}): {
    id: CustomerId;
    loginPrincipal?: Principal;
    active: boolean;
    invoiceCount: bigint;
    name: string;
    createdAt: Timestamp;
    creditLimit: Satang;
    address: string;
    notes: string;
    outstandingBalance: Satang;
    phone: string;
} {
    return {
        id: value.id,
        loginPrincipal: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.loginPrincipal)),
        active: value.active,
        invoiceCount: value.invoiceCount,
        name: value.name,
        createdAt: value.createdAt,
        creditLimit: value.creditLimit,
        address: value.address,
        notes: value.notes,
        outstandingBalance: value.outstandingBalance,
        phone: value.phone
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProofId;
    customerName: string;
    status: _ProofStatus;
    note: string;
    invoiceId: _InvoiceId;
    reviewNote: string;
    reviewedAt: [] | [_Timestamp];
    imageKey: string;
    invoiceNumber: string;
    paymentId: [] | [_PaymentId];
    customerId: _CustomerId;
    transferredAt: _Timestamp;
    amount: _Satang;
    uploadedAt: _Timestamp;
}): {
    id: ProofId;
    customerName: string;
    status: ProofStatus;
    note: string;
    invoiceId: InvoiceId;
    reviewNote: string;
    reviewedAt?: Timestamp;
    imageKey: string;
    invoiceNumber: string;
    paymentId?: PaymentId;
    customerId: CustomerId;
    transferredAt: Timestamp;
    amount: Satang;
    uploadedAt: Timestamp;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_ProofStatus_n8(_uploadFile, _downloadFile, value.status),
        note: value.note,
        invoiceId: value.invoiceId,
        reviewNote: value.reviewNote,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.reviewedAt)),
        imageKey: value.imageKey,
        invoiceNumber: value.invoiceNumber,
        paymentId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.paymentId)),
        customerId: value.customerId,
        transferredAt: value.transferredAt,
        amount: value.amount,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    aging: Array<_AgingBucketAmount>;
    invoiceCount: bigint;
    oldestDueAt: [] | [_Timestamp];
    outstandingBalance: _Satang;
    customerId: _CustomerId;
    phone: string;
}): {
    customerName: string;
    aging: Array<AgingBucketAmount>;
    invoiceCount: bigint;
    oldestDueAt?: Timestamp;
    outstandingBalance: Satang;
    customerId: CustomerId;
    phone: string;
} {
    return {
        customerName: value.customerName,
        aging: from_candid_vec_n32(_uploadFile, _downloadFile, value.aging),
        invoiceCount: value.invoiceCount,
        oldestDueAt: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.oldestDueAt)),
        outstandingBalance: value.outstandingBalance,
        customerId: value.customerId,
        phone: value.phone
    };
}
function from_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    title: string;
    body: string;
    kind: _NotificationKind;
    createdAt: _Timestamp;
    read: boolean;
}): {
    id: NotificationId;
    title: string;
    body: string;
    kind: NotificationKind;
    createdAt: Timestamp;
    read: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        kind: from_candid_NotificationKind_n79(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        read: value.read
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AgingBucketAmount>): Array<AgingBucketAmount> {
    return value.map((x)=>from_candid_AgingBucketAmount_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerSummary>): Array<CustomerSummary> {
    return value.map((x)=>from_candid_CustomerSummary_n66(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DebtRow>): Array<DebtRow> {
    return value.map((x)=>from_candid_DebtRow_n69(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n77(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Receipt>): Array<Receipt> {
    return value.map((x)=>from_candid_Receipt_n57(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransferProof>): Array<TransferProof> {
    return value.map((x)=>from_candid_TransferProof_n6(_uploadFile, _downloadFile, x));
}
function to_candid_CustomerQuery_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerQuery): _CustomerQuery {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceQuery_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceQuery): _InvoiceQuery {
    return to_candid_record_n72(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceStatus_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): _InvoiceStatus {
    return value == InvoiceStatus.paid ? {
        paid: null
    } : value == InvoiceStatus.unpaid ? {
        unpaid: null
    } : value == InvoiceStatus.overdue ? {
        overdue: null
    } : value == InvoiceStatus.partiallyPaid ? {
        partiallyPaid: null
    } : value;
}
function to_candid_NotificationQuery_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationQuery): _NotificationQuery {
    return to_candid_record_n75(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentInput_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentInput): _PaymentInput {
    return to_candid_record_n92(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return value == PaymentMethod.other ? {
        other: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.bankTransfer ? {
        bankTransfer: null
    } : value;
}
function to_candid_PaymentQuery_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentQuery): _PaymentQuery {
    return to_candid_record_n82(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.approved ? {
        approved: null
    } : value == PaymentStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_ProductQuery_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductQuery): _ProductQuery {
    return to_candid_record_n85(_uploadFile, _downloadFile, value);
}
function to_candid_ProofQuery_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProofQuery): _ProofQuery {
    return to_candid_record_n87(_uploadFile, _downloadFile, value);
}
function to_candid_ProofStatus_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProofStatus): _ProofStatus {
    return value == ProofStatus.pending ? {
        pending: null
    } : value == ProofStatus.approved ? {
        approved: null
    } : value == ProofStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    descending?: boolean;
    sortBy?: string;
    search?: string;
}): {
    descending: [] | [boolean];
    sortBy: [] | [string];
    search: [] | [string];
} {
    return {
        descending: value.descending ? candid_some(value.descending) : candid_none(),
        sortBy: value.sortBy ? candid_some(value.sortBy) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none()
    };
}
function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: InvoiceStatus;
    search?: string;
    toDate?: Timestamp;
    fromDate?: Timestamp;
    customerId?: CustomerId;
}): {
    status: [] | [_InvoiceStatus];
    search: [] | [string];
    toDate: [] | [_Timestamp];
    fromDate: [] | [_Timestamp];
    customerId: [] | [_CustomerId];
} {
    return {
        status: value.status ? candid_some(to_candid_InvoiceStatus_n73(_uploadFile, _downloadFile, value.status)) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        customerId: value.customerId ? candid_some(value.customerId) : candid_none()
    };
}
function to_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    limit?: bigint;
    unreadOnly?: boolean;
}): {
    limit: [] | [bigint];
    unreadOnly: [] | [boolean];
} {
    return {
        limit: value.limit ? candid_some(value.limit) : candid_none(),
        unreadOnly: value.unreadOnly ? candid_some(value.unreadOnly) : candid_none()
    };
}
function to_candid_record_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: PaymentStatus;
    search?: string;
    customerId?: CustomerId;
}): {
    status: [] | [_PaymentStatus];
    search: [] | [string];
    customerId: [] | [_CustomerId];
} {
    return {
        status: value.status ? candid_some(to_candid_PaymentStatus_n83(_uploadFile, _downloadFile, value.status)) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none(),
        customerId: value.customerId ? candid_some(value.customerId) : candid_none()
    };
}
function to_candid_record_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    search?: string;
    category?: string;
    activeOnly?: boolean;
}): {
    search: [] | [string];
    category: [] | [string];
    activeOnly: [] | [boolean];
} {
    return {
        search: value.search ? candid_some(value.search) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none(),
        activeOnly: value.activeOnly ? candid_some(value.activeOnly) : candid_none()
    };
}
function to_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: ProofStatus;
    customerId?: CustomerId;
}): {
    status: [] | [_ProofStatus];
    customerId: [] | [_CustomerId];
} {
    return {
        status: value.status ? candid_some(to_candid_ProofStatus_n88(_uploadFile, _downloadFile, value.status)) : candid_none(),
        customerId: value.customerId ? candid_some(value.customerId) : candid_none()
    };
}
function to_candid_record_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: PaymentMethod;
    reference: string;
    invoiceId: InvoiceId;
    amount: Satang;
    paidAt: Timestamp;
}): {
    method: _PaymentMethod;
    reference: string;
    invoiceId: _InvoiceId;
    amount: _Satang;
    paidAt: _Timestamp;
} {
    return {
        method: to_candid_PaymentMethod_n93(_uploadFile, _downloadFile, value.method),
        reference: value.reference,
        invoiceId: value.invoiceId,
        amount: value.amount,
        paidAt: value.paidAt
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
